-- Insert 10 Indian users with different categories
INSERT INTO users (id, email, name, bio, category_id, highlights, rating, total_ratings, experience_level, location, availability, onboarding_completed, created_at, updated_at) VALUES
  ('user-001', 'arjun.sharma@example.com', 'Arjun Sharma', 'Professional musician and producer from Mumbai with 8+ years of experience creating chart-topping music.', (SELECT id FROM categories WHERE name = 'Music'), '{"Beat Production", "FL Studio", "Mixing"}', 4.8, 42, 'advanced', 'Mumbai, India', 'available', TRUE, NOW(), NOW()),
  ('user-002', 'priya.kapoor@example.com', 'Priya Kapoor', 'Classical dancer and choreographer specializing in Bharatanatyam. Passionate about preserving Indian dance traditions.', (SELECT id FROM categories WHERE name = 'Dance'), '{"Choreography", "Bharatanatyam", "Teaching"}', 4.9, 58, 'expert', 'Delhi, India', 'available', TRUE, NOW(), NOW()),
  ('user-003', 'rajesh.kumar@example.com', 'Rajesh Kumar', 'Contemporary artist exploring abstract expressionism. Gallery exhibitions across India and Southeast Asia.', (SELECT id FROM categories WHERE name = 'Arts'), '{"Oil Painting", "Installation Art", "Exhibitions"}', 4.6, 35, 'advanced', 'Bangalore, India', 'busy', TRUE, NOW(), NOW()),
  ('user-004', 'neha.singh@example.com', 'Neha Singh', 'Full-stack developer specializing in React and Node.js. Built multiple SaaS applications. Open source contributor.', (SELECT id FROM categories WHERE name = 'Development'), '{"React", "Node.js", "AWS"}', 4.7, 48, 'expert', 'Hyderabad, India', 'available', TRUE, NOW(), NOW()),
  ('user-005', 'vikram.patel@example.com', 'Vikram Patel', 'UI/UX designer with 6+ years of experience. Passionate about accessible and user-centric design.', (SELECT id FROM categories WHERE name = 'Design'), '{"Figma", "User Research", "Prototyping"}', 4.5, 32, 'advanced', 'Pune, India', 'available', TRUE, NOW(), NOW()),
  ('user-006', 'anjali.verma@example.com', 'Anjali Verma', 'Freelance writer and content strategist. Published articles on tech, culture, and social issues.', (SELECT id FROM categories WHERE name = 'Writing'), '{"Content Strategy", "Blogging", "Editing"}', 4.8, 45, 'advanced', 'Kolkata, India', 'available', TRUE, NOW(), NOW()),
  ('user-007', 'rohan.iyer@example.com', 'Rohan Iyer', 'Photography enthusiast capturing landscapes and portraits across India. Stock photography contributor.', (SELECT id FROM categories WHERE name = 'Photography'), '{"Landscape", "Portrait", "Editing"}', 4.4, 28, 'intermediate', 'Goa, India', 'available', TRUE, NOW(), NOW()),
  ('user-008', 'shreya.gupta@example.com', 'Shreya Gupta', 'Business strategist and entrepreneur. Founded 2 startups. Mentor and investor in tech ecosystem.', (SELECT id FROM categories WHERE name = 'Business'), '{"Strategy", "Fundraising", "Mentoring"}', 4.9, 52, 'expert', 'Gurugram, India', 'available', TRUE, NOW(), NOW()),
  ('user-009', 'aditya.sharma@example.com', 'Aditya Sharma', 'Indie music artist and composer. Blends classical Indian music with modern electronic sounds.', (SELECT id FROM categories WHERE name = 'Music'), '{"Composition", "Production", "Live Performances"}', 4.7, 39, 'advanced', 'Chennai, India', 'busy', TRUE, NOW(), NOW()),
  ('user-010', 'isha.desai@example.com', 'Isha Desai', 'Digital artist and illustrator. Creates stunning digital artwork for games, apps, and publications.', (SELECT id FROM categories WHERE name = 'Arts'), '{"Digital Art", "Illustration", "Animation"}', 4.6, 41, 'advanced', 'Ahmedabad, India', 'available', TRUE, NOW(), NOW());
